[module]
[module.hugoVersion]
extended = true
min = "0.97.0"

[params]
breadcrumb = true
dateFormat = ":date_long"
countTaxonomyPosts = false
color = "auto"
customCSS = []
customJS = []
diagram = false
carouselPostCount = 5
featuredPostCount = 5
fixedHeader = true
fullWidth = false
mainSections = ["posts", "docs"]
poweredBy = true
readingTime = true
recentPostCount = 5
relatedPostCount = 5
palette = "blue"
palettes = ["blue", "blue gray", "brown", "cyan", "green", "indigo", "orange", "pink", "purple", "red", "teal", "yellow"]
pinnedPost = true
pinnedPostCount = 1
postDate = true
searchBar = true
sidebarTaxonomies = ["series", "categories", "tags", "authors"]
taxonomyPaginate = 10
taxonomyPostCount = 3
titleCase = false
titleSeparator = "-"
tocWordCount = 280
viewer = true
