[build]
publish = "exampleSite/public"
command = "cd exampleSite && npm install && hugo --minify --themesDir=../../ --theme=repo"

[build.environment]
NODE_VERSION = "17.6.0"
HUGO_VERSION = "0.93.0"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.17.7"
HUGO_BASEURL = "https://hbs.razonyang.com/v1.0/"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_BASEURL = $DEPLOY_PRIME_URL

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/:lang/*"
  to = "/:lang/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/en/404.html" # Replace the "en" to your default language code.
  # to = "/404.html" # Use it when a monolingual site or "defaultContentLanguageInSubdir" is disabled.
  status = 404
