[[main]]
  name = "Dropdown"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "Github"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  pre = '<i class="fab fa-fw fa-github"></i>'
