[[main]]
  name = "主頁"
  url = "/zh-tw/"
  weight = 10
[[main]]
  name = "分類"
  url = "/zh-tw/categories/"
  weight = 20
[[main]]
  name = "標籤"
  url = "/zh-tw/tags/"
  weight = 30
[[main]]
  name = "關於"
  url = "/zh-tw/about/"
  weight = 40
[[main]]
  name = "下拉菜單"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "菜單"
  weight = 10
  url = "#"
[[main]]
  parent = "dropdown"
  name = "另一菜單"
  weight = 20
  url = "#"
[[main]]
  parent = "dropdown"
  name = "外部鏈接"
  weight = 90
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
