[[main]]
  name = "Home"
  url = "/en"
  weight = 10
[[main]]
  name = "Categories"
  url = "/en/categories"
  weight = 20
[[main]]
  name = "Tags"
  url = "/en/tags"
  weight = 30
[[main]]
  name = "About"
  url = "/en/about"
  weight = 40
[[main]]
  name = "Dropdown"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "Action"
  weight = 10
  url = "#"
[[main]]
  parent = "dropdown"
  name = "Other Action"
  weight = 20
  url = "#"
[[main]]
  parent = "dropdown"
  name = "External"
  weight = 90
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
