mainSections = ["post", "posts"]

author = "Razon Yang"
titleSeparator = "-"

description = "A clean, responsive and feature-rich blog theme for Hugo"
# image = ["site-feature-image.jpg"]

# dateFormat = "Jan 2, 2006"

# Google Adsense
googleAdsense = ""

# Baidu Analytics
baiduAnalytics = ""

# Site verification
googleSiteVerification = ""
bingSiteVerification = ""
baiduSiteVerification = ""

# math = true # Enable math globally.

# poweredBy = false # Whether to show powered by.

# featuredPostCount = 5 # The number of featured posts shown in sidebar.
# recentPostCount = 5 # The number of recent posts shown in sidebar.
# relatedPostCount = 5 # The number of related posts.

[utterances]
#repo = "razonyang/hugo-theme-bootstrap"
#issueTerm = "pathname" # pathname, url, title, og:title
#label = "comment"
#theme = "github-light" # github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
