# sass_transpiler = "dartsass"

mainSections = ["posts", "docs"] # Default to ["posts"].

# titleSeparator = "|" # Title separator. Default to "-".

description = "An extreme fast, responsive and feature-rich blog theme for Hugo"
keywords = "Hugo, Bootstrap, Blog Theme"
# images = ["site-feature-image.jpg"]

# metaRobots = "noindex, nofollow" # Default value for Meta Tag "robots"
# metaRobots = "" # disable Meta Tag "robots"

# logo = "images/logo.png" # Logo image. Default to "images/logo.webp".
# logo = false # Disable Logo
brand = "HBS v1"

palette = "purple" # Default palette. Optional. You'll need to clear the browser cache after modifying this.
# palettes = ["blue", "blue gray", "purple"] # Available palettes. Default to ALL.
# palettes = [] # Disable palette switcher.

# color = "dark" # light, dark or auto. Default to auto.

# fullWidth = true # Full width.
# fixedHeader = false # Turn on/off fixed header.

# dateFormat = ":date_full"

# Google Adsense
googleAdsense = ""

# math = true # Enable math globally.
# toc = false # Disable TOC globally.
# tocPosition = "content"
# breadcrumb = false # Disable breadcrumb
# breadcrumbDivider = ">" # Breadcrumb divider
# diagram = true
# socialShare = false # disable social network sharing
# searchBar = false # disable search-bar

# poweredBy = false # Whether to show powered by.

# readingTime = false # Whether to display the reading time.
# postDate = false # Whether to display the post date in the post meta section.

# featuredPostCount = 10 # The number of featured posts shown in sidebar. Turn off by setting it to false.
# recentPostCount = 10 # The number of recent posts shown in sidebar. Turn off by setting it to false.
# relatedPostCount = 10 # The number of related posts. Turn off by setting it to false.
# categoryCount = 10 # The number of categories shown in sidebar. Turn off by setting it to false.
# tagCount = 10 # The number of tags shown in sidebar. Turn off by setting it to false.
# seriesCount = 20 # The number of series shown in sidebar. Turn off by setting it to false.
# taxonomyPaginate = 5 # Default to 10.
taxonomyPostCount = 20    # The number of taxonomy's posts. Turn off by setting it to false.
countTaxonomyPosts = true # Count posts of taxonomy.
# taxonomySortingMethod = "popularity" # Sorting taxonomies by popularity, sort alphabetically by default.

# sidebarTaxonomies = ["categories", "tags", "series"] # The order of taxonomies on the sidebar.

# pinnedPost = false # Turn on/off pinned posts.
pinnedPostCount = 3 # The number of pinned posts.

# Custom CSS and JS
customCSS = []
customJS = []

tocWordCount = 1 # TOC is displayed only if the post's word count exceeds this value.

titleCase = true # Capitalized title.

viewer = true # Image Viewer

# backgroundImage = ['/images/bg-light.png', '/images/bg-dark.png']
# rss = "home" # link the RSS button to homepage all the times.

# externalLinkIcon = false

# socialAnimation = false # Remove animation from social links if false.
socialColor = false # Remove color from social links if false.

[sidebar]
# fixed = true
# archives = true # Enable archives widget
# taxonomiesToggle = false # Disable taxonomy toggle
# taxonomiesToggleArchives = false # Don't show the archives on taxonomies toggle widget.
# categories = true # Enable categories widget
# tags = true # Enable tags widget
# series = true # Enable series widget
# authors = true # Enable authors widget
# postsToggle = false # Disable posts toggle
# featuredPosts = true # Enable featured posts widget
# recentPosts = true # Enable featured posts widget
# collapsed = true # Collapse sidebar widgets by default on small screens.

[codeBlock]
# maxLines = 8
lineNos = true # true/false represents that show/hide the line numbers by default.

[post]
# excerpt = "" # uncomment to use summaries as excerpts.
# excerptMaxLength = 120
# copyright = false # Whether to display copyright section on each post.
# plainifyExcerpt = false # Format excerpt in HTML if false.
featuredImage = true     # Show the featured image above the content.
numberifyHeadings = true # Count headings automatically.
# numberifyHeadingsEndLevel = 4 # The depth of headings to count. Default to 6.
numberifyHeadingsSeparator = "." # The separator between of number and headings.
# tocStyleType = "decimal" # The TOC's CSS list-style-type property.
imageTitleAsCaption = true
# panel = false # Disable the post panel.
# nav = false # Disable post navigations.
# The page position after clicking the read more button, read more from content if true. Default to the beginning of page.
# It supports only of the manual summaries splitting via <!--more-->.
# readMoreFromContent = true

[archive]
# basePath = "/archiv" # The base path of archive pages.
# dateFormat = "01-02" # Archive date format. Default to "Jan 2".

[analytics]
# baidu = "" # Baidu Analytics
# plausible = "razonyang.com,hbs.razonyang.com" # Multiple domains separated by comma.
# plausibleScript = "" # Specify the self-hosted script or extended script. Default to https://plausible.io/js/script.js.

# Site verification
[siteVerification]
google = ""
bing = ""
baidu = ""
baiduUnion = "" # Baidu Union
so = ""
sogou = ""
shenma = ""

[creativeCommons]
# by = true # Credit must be given to you, the creator.
# nc = true # Only noncommercial use of your work is permitted.
# nd = true # No derivatives or adaptations of your work are permitted.
# sa = true # Adaptations must be shared under the same terms.

# [utterances]
# repo = "razonyang/hugo-theme-bootstrap" # Replace with your repository.
# issueTerm = "pathname" # pathname, url, title, og:title
# label = "comment"
# By default, light and dark mode correspond to github-light and github-dark, respectively.
# Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
# theme = ""

# [staticman]
# endpoint = "https://yourstaticmaninstance" # Required, replace with your own Staticman instance.
# repo = "user/repo" # Required
# service = "github" # Default to GitHub.
# branch = "main" # Default to master.
# property = "comments" # Default to comments.
# sorting = "desc" # Default to asc.
# reCaptchaKey = "" # The reCaptcha site key.
# reCaptchaSecret = "" # The reCaptcha encrypted secret. You'll need to encrypt plain secret via https://yourstaticmaninstance/v3/encrypt/PLAINSECRET.
# extraFields = [ "url" ] # Extra fields. Available fields: url.
# requiredFields = [ "email", "url" ] # Extra required fields. Available fields: email and the extra fields.
# paginate = 5 # Default to 10.
# moderation = false # Same as Staticman's moderation.

[giscus]
repo = "razonyang/hugo-theme-bootstrap"
repoId = "MDEwOlJlcG9zaXRvcnkzMDQzMzI4NTM="
category = "General"
categoryId = "MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyODkzODg2"
# theme = "dark" # Default to auto.
# mapping = "title" # Default to pathname.
# inputPosition = "bottom" # Default to top.
# reactions = false # Disable reactions.
# metadata = true # Emit discussion metadata.
# lang = "en" # Specify language, default to site language.
# lazyLoading = false # Default to true.

[search]
# paginate = 5 # Pagination. Default to 10.
# resultContentCharactersCount = 20 # The maximum characters count of result content for displaying.
indexPaginate = 100 # The number of pages per index file. Default to 1000.
# indexPreload = false # Do not preload index files.
# maxResults = 50
# shortcut = ["Control", "/"]
# Fuse.js options, the following options are available. See https://fusejs.io/api/options.html.
[search.fuse]
# ignoreLocation = true
# location = 0
# isCaseSensitive = true
minMatchCharLength = 3
# threshold = 0.6
# distance = 100
# findAllMatches = true
# ignoreFieldNorm = true
# fieldNormWeight = 0

#[docsearch]
#  # https://docsearch.algolia.com/docs/api
#  # container = ".search-button" # replace it if necessary, default to '.search-button'.
#  appId = "QJSHIZ7V63"
#  apiKey = "664dc009c2ff1891823c07720e5f79ed"
#  indexName = "razonyang_hbs"
#  # debug = true

# [algolia]
# appId = "6K24QAPFEO"
# apiKey = "133b81d06bc092d2adc13ccc18c189d0"
# indexName = "tests"
# paginate = 10
# stallThreshold = 500

# [reward]
# alipay = "images/reward/alipay.png"
# wechat = "images/reward/wechat.png"
#paypal = "images/reward/paypal.png"
#patreon = "images/reward/patreon.png"
#liberapay = "images/reward/liberapay.png"

[funding]
alipay = "https://razonyang.com/images/reward/alipay.webp"
wechat = "https://razonyang.com/images/reward/wechat.webp"
buymeacoffee = "razonyang"
ko_fi = "razonyang"
patreon = "razonyang"
open_collective = "hbs"
paypal = "razonyang"

#[share]
#addThis = "" # AddThis pubid.

# [actionsPanel]
# disabled = true

[fontSize] # Comment or remove this settings to disable font size switcher.
# extraSmall = ".8rem"
# small = ".9rem"
# large = "1.1rem"
# extraLarge = "1.2rem"

[pwa]
[pwa.manifest]
# name = "" # Default to site title.
short_name = "HBS"
# display = "fullscreen" # Default to standalone.
# description = "" # Default to site description.
# theme_color = ""
# background_color = ""

# Icons
# [[pwa.manifest.icons]]
#   sizes = "96x96"
#   src = "/images/icons/icon-96x96.png"
# [[pwa.manifest.icons]]
#   sizes = "144x144"
#   src = "/images/icons/icon-144x144.png"
[pwa.precache]
# fonts = [
#   "/assets/katex/fonts/KaTeX_Math-Italic.woff2"
# ]
# images = [
#   "/images/logo.webp",
#   "/images/profile.webp"
# ]
# pages = [
#   "/"
# ]
# scripts = [
#   "/assets/js/foo.js"
# ]
# styles = [
#   "https://fonts.googleapis.com/css2?family=Roboto&display=swap"
# ]

[contact]
endpoint = "https://getform.io/f/56041c81-9e03-4c24-b9c5-61238854d4cd" # Backend endpoint, remove this line if you're using Netlify.
# file = true # Enable file upload
# fileField = "image" # The name of file field.
[contact.reCaptcha]
siteKey = "6LcWQH0gAAAAAJPZN9S-wrugRUukNOiHfxmFOSM5"

[repo]
url = "https://github.com/razonyang/hugo-theme-bootstrap"
# branch = "main"
subPath = "exampleSite"
# dateFormat = "02/01/2006, 15:04:05 PM"

# [fullWidthInSections]
# docs = true

[topAppBar]
# colorToggle = false # Disable the color toggle
# coloredInDark = true # Colored in dark mode
# dropdownMenuToggle = false # Hide the dropdown menu toggle.
# expandBreakpoint = "xl" # expand the content above the specific breakpoint: lg, xl, xxl.
[topAppBar.social]
github = "razonyang/hugo-theme-bootstrap"
patreon = "razonyang"
paypal = "razonyang"
# rss = "" # Disable RSS link

[docs]
[docs.nav]
expand = false # Expand docs navigations.
reduceFontSize = true

[feeds]
# content = true

# Set socialColor as false to disable the color.
[social]
# artstation = "yourartstationusername"
# bilibili = "yourbilibiliuserid"
# bitbucket = "yourbitbucketworkspaceid"
# codeberg = "yourcodebergusername"
# discord = "yourdiscordinvitecode"
# discourse = "https://yourforum.tld"
# dockerhub = "yourdockerhubusername"
email = "user@domain.tld"
# facebook = "yourfacebookusername"
# facebookgroup = "yourfacebookgroupname"
github = "razonyang/hugo-theme-bootstrap"
# gitlab = "yourgitlabusername"
# instagram = "yourinstagramusername"
# itchio = "youritchiousername"
# kaggle = "yourkaggleusername"
# lastfm = "yourlastfmusername"
# liberapay = "yourliberapayaccount"
# linkedin = "yourlinkedinusername"
# mastodon = "yourmastodonusername"
# medium = "yourmediumusername" # Medium username or custom domain(e.g. https://razonyang.com).
patreon="razonyang"
paypal="razonyang"
# pinterest = "yourpinterestusername"
# qq = "yourqqnumber"
# quora = "yourquorausername"
# reddit = "yourredditusername"
# rss = "" # Disable RSS link
# stackoverflow = "yourstackoverflowuserid"
# telegram = "yourtelegramusername"
# tiktok = "yourtiktokusername"
# tipeee="yourtipeeeaccount-fr"
# tumblr = "yourtumblrusername"
# weibo = "yourweibousername"
x = "razonyang"
# xing = "yourxingusername"
# youtube = "youryoutubechannelid"
# zhihu = "yourzhihuusername"

[author]
name = "HBS (Hugo Bootstrap Theme)"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Fast, responsive, multipurpose, open source (MIT license) and feature-rich Hugo theme."
company = 'Company'
# company = '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>'
location = "Earth"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[author.params]
  #layout = "compact"

[author.social]
  email = "razonyang@gmail.com"
  github = "razonyang/hugo-theme-bootstrap"
  x = "razonyang"
  patreon = "razonyang"
  paypal = "razonyang"
  # rss = "" # Disable RSS link

# 备案 in pinyin, for websites hosted in China.
# [beian]
# icpNumber = "京ICP证123456号-1" # ICP number.
# psbNumber = "京公网安备12345678901234号" # Public Security Bureau number.
# moeNumber = "萌ICP备12345678号" # See https://icp.gov.moe/.
