# mainSections = ["post", "posts"] # Default to ["posts"].

# titleSeparator = "|" # Title separator. Default to "-".

description = "An extreme fast, responsive and feature-rich blog theme for Hugo"
keywords = "Hugo, Bootstrap, Blog Theme"
# images = ["site-feature-image.jpg"]

# logo = "images/logo.png" # Logo image. Default to "images/logo.webp".
brand = "BOOTSTRAP"
# menusPosition = "left" # Menus position: right(default), left or center.

palette = "blue" # Default palette. Optional.
# palettes = ["blue", "blue gray", "brown"] # Available palettes. Default to ALL.
# palettes = [] # Disable palette switcher.

# color = "dark" # light, dark or dynamic. Default to dynamic.

# fullWidth = true # Full width.
# fixedHeader = false # Turn on/off fixed header.

# dateFormat = "Jan 2, 2006"

# Google Adsense
googleAdsense = ""

# math = true # Enable math globally.
# toc = false # Disable TOC globally.
# breadcrumb = false # Disable breadcrumb
# diagram = true

# poweredBy = false # Whether to show powered by.

# readingTime = false # Whether to display the reading time.
# postDate = false # Whether to display the post date in the post meta section.

# featuredPostCount = 10 # The number of featured posts shown in sidebar. Turn off by setting it to false.
# recentPostCount = 10 # The number of recent posts shown in sidebar. Turn off by setting it to false.
# relatedPostCount = 10 # The number of related posts. Turn off by setting it to false.
# categoryCount = 10 # The number of categories shown in sidebar. Turn off by setting it to false.
# tagCount = 10 # The number of tags shown in sidebar. Turn off by setting it to false.
# seriesCount = 10 # The number of series shown in sidebar. Turn off by setting it to false.
# taxonomyPostCount = 5 # The number of posts of taxonomy. Turn off by setting it to false.

# Custom CSS and JS
customCSS = []
customJS = []

# tocWordCount = 280 # TOC is displayed only if the post's word count exceeds this value.

titleCase = true # Capitalized title.

[codeBlock]
  # maxLines = 8
  lineNos = false # true/false represents that show/hide the line numbers by default.

[post]
  # excerpt = "description"
  # excerptMaxLength = 120

[archive]
  paginate = 8 # Archive pagination. Default to 100.
  # dateFormat = "01-02" # Archive date format. Default to "Jan 2".

[analytics]
  # baidu = "" # Baidu Analytics

# Site verification
[siteVerification]
  google = ""
  bing = ""
  baidu = ""
  baiduUnion = "" # Baidu Union
  so = ""
  sogou = ""
  shenma = ""

[creativeCommons]
  # by = true # Credit must be given to you, the creator.
  # nc = true # Only noncommercial use of your work is permitted.
  # nd = true # No derivatives or adaptations of your work are permitted.
  # sa = true # Adaptations must be shared under the same terms.

[utterances]
  repo = "razonyang/hugo-theme-bootstrap-comments" # Replace with your repository.
  #issueTerm = "pathname" # pathname, url, title, og:title
  #label = "comment"
  # By default, light and dark mode correspond to github-light and github-dark, respectively.
  # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
  #theme = "" 

[search]
  paginate = 5 # Pagination. Default to 10.
  # resultContentWordCount = 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  [search.fuse]
    # ignoreLocation = true
    # location = 0
    # isCaseSensitive = false
    # minMatchCharLength = 1
    threshold = 0.1
    # distance = 100
    # useExtendedSearch = true

[reward]
  alipay = "images/reward/alipay.png"
  wechat = "images/reward/wechat.png"

#[share]
  #addThis = "" # AddThis pubid.

[fontSize] # Comment or remove this settings to disable font size switcher.
  # extraSmall = ".8rem"
  # small = ".9rem"
  # large = "1.1rem"
  # extraLarge = "1.2rem"
  
# Katex options, see also https://katex.org/docs/autorender.html and https://katex.org/docs/options.html
[katex]
  [[katex.delimiters]]
    left = "$$"
    right = "$$"
    display = true
  [[katex.delimiters]]
    left = "$"
    right = "$"
    display = false
  [[katex.delimiters]]
    left = "\\("
    right = "\\)"
    display = false
  [[katex.delimiters]]
    left = "\\begin{equation}"
    right = "\\end{equation}"
    display = true
  [[katex.delimiters]]
    left = "\\begin{align}"
    right = "\\end{align}"
    display = true
  [[katex.delimiters]]
    left = "\\begin{alignat}"
    right = "\\end{alignat}"
    display = true
  [[katex.delimiters]]
    left = "\\begin{gather}"
    right = "\\end{gather}"
    display = true
  [[katex.delimiters]]
    left = "\\begin{CD}"
    right = "\\end{CD}"
    display = true
  [[katex.delimiters]]
    left = "\\["
    right = "\\]"
    display = true

[mermaid] # See https://mermaid-js.github.io/mermaid/#/Setup?id=configuration
  theme = "dark"