email = "user@domain.tld"
facebook = "yourfacebookusername"
github = "razonyang/hugo-theme-bootstrap"
gitlab = "yourgitlabusername"
linkedin = "yourlinkedinusername"
xing = "yourxingusername"
stackoverflow = "yourstackoverflowuserid"
twitter = "yourtwitterusername"
weibo = "yourweibousername"
zhihu = "yourzhihuusername"
instagram = "yourinstagramusername"
quora = "yourquorausername"
tumblr = "yourtumblrusername"
reddit = "yourredditusername"
telegram = "yourtelegramusername"
qq = "yourqqnumber"
dockerhub = "yourdockerhubusername"
bitbucket = "yourbitbucketworkspaceid"
kaggle = "yourkaggleusername"
medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
lastfm = "yourlastfmusername"
bilibili = "yourbilibiliuserid"
youtube = "youryoutubechannelid"
discord = "yourdiscordinvitecode"
discourse = "https://yourforum.tld"
facebookgroup = "yourfacebookgroupname"
tiktok = "yourtiktokusername"
artstation = "yourartstationusername"
pinterest = "yourpinterestusername"
mastodon = "yourmastodonusername"
liberapay = "yourliberapayaccount"
paypal="razonyang"
patreon="razonyang"
tipeee="yourtipeeeaccount-fr"
# rss = "" # Disable RSS link
